# Generated by Django 4.2.9 on 2024-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0002_alter_subject_options_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('subjects', models.ManyToManyField(to='subject.subject')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
