# Generated by Django 4.2.9 on 2024-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_question_options_rename_question_question_text'),
        ('interview', '0002_interview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='learend_quesions',
            field=models.ManyToManyField(to='subject.question'),
        ),
    ]
