# Generated by Django 4.2.9 on 2024-02-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_options_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
