# Generated by Django 5.0.1 on 2024-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_question_options_rename_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(choices=[(1, 'FOUNDATIONAL'), (2, 'PROFICIENT'), (3, 'EXPERT')], default=1),
        ),
    ]
